#ifndef FT_IRC_CHARSET_H
# define FT_IRC_CHARSET_H

# define CHARSET_LCASE_LETTERS "abcdefghijklmnopqrstuvwxyz"
# define CHARSET_UCASE_LETTERS "ABCDEFGHIJKLMNOPQRSTUVWUXY"
# define CHARSET_LETTERS CHARSET_LCASE_LETTERS CHARSET_UCASE_LETTERS

# define CHARSET_DIGITS "0123456789"

# define CHARSET_ALPHANUMERICS CHARSET_LETTERS CHARSET_DIGITS

# define CHARSET_SPECIAL "[]\\`_^{|}"

#endif
